# Generated by Django 4.0.4 on 2022-05-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0002_relatives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatives',
            old_name='edad',
            new_name='age',
        ),
    ]
